'use client';
import React from 'react';
import Starfield from '@/components/Starfield';

class Page extends React.Component {
  starfield() {
    // 120 animated spans → one canvas; identical field, one paint.
    if (this.props.starfield === false) return null;
    return React.createElement(Starfield);
  }
  renderVals() { return { stars: this.starfield() }; }

  render() {
    const V = this.renderVals();
    return (
      <>


<svg aria-hidden="true" focusable="false" style={{ position: 'absolute', width: '0', height: '0', overflow: 'hidden' }}>
  <defs>
    <filter id="torn-edge-1" x="-12%" y="-12%" width="124%" height="124%"><feTurbulence type="fractalNoise" baseFrequency="0.016 0.022" numOctaves="2" seed="7" result="n"></feTurbulence><feDisplacementMap in="SourceGraphic" in2="n" scale="5"></feDisplacementMap></filter>
    <filter id="torn-edge-2" x="-12%" y="-12%" width="124%" height="124%"><feTurbulence type="fractalNoise" baseFrequency="0.021 0.014" numOctaves="2" seed="41" result="n"></feTurbulence><feDisplacementMap in="SourceGraphic" in2="n" scale="6"></feDisplacementMap></filter>
    <filter id="torn-edge-3" x="-12%" y="-12%" width="124%" height="124%"><feTurbulence type="fractalNoise" baseFrequency="0.013 0.026" numOctaves="2" seed="89" result="n"></feTurbulence><feDisplacementMap in="SourceGraphic" in2="n" scale="7"></feDisplacementMap></filter>
    <filter id="rough-tape" x="-15%" y="-15%" width="130%" height="130%"><feTurbulence type="fractalNoise" baseFrequency="0.06 0.16" numOctaves="2" seed="15" result="n"></feTurbulence><feDisplacementMap in="SourceGraphic" in2="n" scale="2.6"></feDisplacementMap></filter>
    <filter id="sketch-edge" x="-18%" y="-18%" width="136%" height="136%"><feTurbulence type="fractalNoise" baseFrequency="0.05 0.09" numOctaves="2" seed="23" result="n"></feTurbulence><feDisplacementMap in="SourceGraphic" in2="n" scale="3.4"></feDisplacementMap></filter>
  </defs>
</svg>

<div data-screen-label="Contact" style={{ position: 'relative', minHeight: '100dvh', color: '#ede4d8', background: 'transparent' }}>

  <span aria-hidden="true" data-r="foil" style={{ position: 'fixed', inset: '0', zIndex: '0', pointerEvents: 'none', padding: '9px', background: 'linear-gradient(135deg,#6b5638,#40331f 40%,#5a4426 70%,#382a18) border-box', WebkitMask: 'linear-gradient(#000 0 0) padding-box exclude, linear-gradient(#000 0 0)', mask: 'linear-gradient(#000 0 0) padding-box exclude, linear-gradient(#000 0 0)', opacity: '0.9', filter: 'url(#torn-edge-2)' }}></span>

  <span aria-hidden="true" data-r="spiral" style={{ position: 'fixed', top: '0', bottom: '0', left: '-16px', width: '64px', zIndex: '5', pointerEvents: 'none', backgroundRepeat: 'repeat-y', backgroundPosition: 'center top', backgroundSize: '64px 46px', backgroundImage: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'48\' height=\'34\' viewBox=\'0 0 48 34\'%3E%3Cpath d=\'M18 10 C 5 10 2 13.5 2 17 C 2 20.5 5 24 18 24\' fill=\'none\' stroke=\'rgba(0,0,0,0.6)\' stroke-width=\'6\' stroke-linecap=\'round\' transform=\'translate(1.8 2.6)\'/%3E%3Cpath d=\'M18 10 C 5 10 2 13.5 2 17 C 2 20.5 5 24 18 24\' fill=\'none\' stroke=\'%230d0d0f\' stroke-width=\'8.6\' stroke-linecap=\'round\'/%3E%3Cpath d=\'M18 10 C 5 10 2 13.5 2 17 C 2 20.5 5 24 18 24\' fill=\'none\' stroke=\'%231b1b1e\' stroke-width=\'5.4\' stroke-linecap=\'round\'/%3E%3Cpath d=\'M18 10 C 5 10 2 13.5 2 17 C 2 20.5 5 24 18 24\' fill=\'none\' stroke=\'%23303035\' stroke-width=\'2.4\' stroke-linecap=\'round\' opacity=\'0.85\'/%3E%3Cpath d=\'M15 10.6 C 7 11 3.6 13.6 2.7 16.4\' fill=\'none\' stroke=\'%239aa0aa\' stroke-width=\'1.6\' stroke-linecap=\'round\' opacity=\'0.8\'/%3E%3Cellipse cx=\'18.5\' cy=\'10\' rx=\'2.3\' ry=\'2.7\' fill=\'%23020202\'/%3E%3Cellipse cx=\'18.5\' cy=\'24\' rx=\'2.3\' ry=\'2.7\' fill=\'%23020202\'/%3E%3C/svg%3E' }}></span>

      <div aria-hidden="true" style={{ position: 'absolute', inset: '0', zIndex: '0', pointerEvents: 'none', overflow: 'hidden' }} data-motion-deco="">
    <svg aria-hidden="true" viewBox="0 0 36 32" style={{ position: 'absolute', top: '81.68%', left: '78.37%', width: '2.36rem', height: '2.1rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(-8deg)', animation: 'hb 2.60s ease-in-out 1.40s infinite' }}><defs><linearGradient id="dg-ct-0" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#ce72c0"></stop><stop offset="100%" stopColor="#e58d55"></stop></linearGradient></defs><path d="M18 28 C 4 18 2 8 9 5 C 14 3 18 7 18 10 C 18 7 22 3 27 5 C 34 8 32 18 18 28 Z" fill="none" stroke="url(#dg-ct-0)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 0.25s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 32 32" style={{ position: 'absolute', top: '9.66%', left: '91.98%', width: '2.10rem', height: '2.1rem', overflow: 'visible', opacity: '0.75', transform: 'rotate(7deg)', animation: 'tk 3.71s ease-in-out 1.44s infinite' }}><defs><linearGradient id="dg-ct-1" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#e58d55"></stop><stop offset="100%" stopColor="#d080cc"></stop></linearGradient></defs><path d="M16 2 C17.5 12 20 14.5 30 16 C20 17.5 17.5 20 16 30 C14.5 20 12 17.5 2 16 C12 14.5 14.5 12 16 2 Z" fill="none" stroke="url(#dg-ct-1)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 0.43s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 36 36" style={{ position: 'absolute', top: '14.47%', left: '2.4%', width: '1.90rem', height: '1.9rem', overflow: 'visible', opacity: '0.75', transform: 'rotate(12deg)', animation: 'tk 4.02s ease-in-out 1.68s infinite' }}><path d="M18 3 22 14 33 14 24 21 27 32 18 25 9 32 12 21 3 14 14 14 Z" fill="none" stroke="#e8b64a" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 0.61s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 120 20" style={{ position: 'absolute', top: '38.76%', left: '84.15%', width: '7.20rem', height: '1.2rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(-4deg)', animation: 'sw 8.12s ease-in-out -2.10s infinite, rk 10.5s ease-in-out infinite' }}><defs><linearGradient id="dg-ct-3" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#6fb8ae"></stop><stop offset="100%" stopColor="#9a6be0"></stop></linearGradient></defs><path d="M4 12 C30 4 60 16 116 7" fill="none" stroke="url(#dg-ct-3)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 0.79s forwards' }}></path><path d="M8 17 C34 10 62 20 112 13" fill="none" stroke="url(#dg-ct-3)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 1.01s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 36 32" style={{ position: 'absolute', top: '38.69%', left: '77.97%', width: '2.02rem', height: '1.8rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(6deg)', animation: 'hb 3.16s ease-in-out 2.20s infinite' }}><path d="M18 28 C 4 18 2 8 9 5 C 14 3 18 7 18 10 C 18 7 22 3 27 5 C 34 8 32 18 18 28 Z" fill="none" stroke="#ce72c0" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 0.97s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 110 50" style={{ position: 'absolute', top: '68.53%', left: '35.68%', width: '4.84rem', height: '2.2rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(5deg)', animation: 'sw 9.00s ease-in-out -3.50s infinite, rk 11.5s ease-in-out infinite' }}><defs><linearGradient id="dg-ct-5" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#b58ce8"></stop><stop offset="100%" stopColor="#e58d55"></stop></linearGradient></defs><path d="M6 40 C30 10 52 6 60 20 C66 31 52 38 46 30 C40 20 62 8 100 14" fill="none" stroke="url(#dg-ct-5)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 1.15s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 36 36" style={{ position: 'absolute', top: '69.32%', left: '46.78%', width: '1.60rem', height: '1.6rem', overflow: 'visible', opacity: '0.75', transform: 'rotate(-12deg)', animation: 'tk 5.26s ease-in-out 2.64s infinite' }}><path d="M18 3 22 14 33 14 24 21 27 32 18 25 9 32 12 21 3 14 14 14 Z" fill="none" stroke="#d080cc" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 1.33s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 60 24" style={{ position: 'absolute', top: '88.18%', left: '43.81%', width: '3.75rem', height: '1.5rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(4deg)', animation: 'sw 9.88s ease-in-out -4.90s infinite, rk 12.5s ease-in-out infinite' }}><defs><linearGradient id="dg-ct-7" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#7daa76"></stop><stop offset="100%" stopColor="#6fb8ae"></stop></linearGradient></defs><path d="M2 18 C8 4 14 4 18 12 C22 20 28 20 32 12 C36 4 42 4 46 12 C50 20 56 18 58 10" fill="none" stroke="url(#dg-ct-7)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 1.51s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 32 32" style={{ position: 'absolute', top: '31.14%', left: '2.74%', width: '1.90rem', height: '1.9rem', overflow: 'visible', opacity: '0.75', transform: 'rotate(-9deg)', animation: 'tk 5.88s ease-in-out 3.12s infinite' }}><defs><linearGradient id="dg-ct-8" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#6fb8ae"></stop><stop offset="100%" stopColor="#9a6be0"></stop></linearGradient></defs><path d="M16 2 C17.5 12 20 14.5 30 16 C20 17.5 17.5 20 16 30 C14.5 20 12 17.5 2 16 C12 14.5 14.5 12 16 2 Z" fill="none" stroke="url(#dg-ct-8)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 1.69s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 36 32" style={{ position: 'absolute', top: '57.74%', left: '4.44%', width: '1.91rem', height: '1.7rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(8deg)', animation: 'hb 3.86s ease-in-out 3.20s infinite' }}><defs><linearGradient id="dg-ct-9" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#ce72c0"></stop><stop offset="100%" stopColor="#e58d55"></stop></linearGradient></defs><path d="M18 28 C 4 18 2 8 9 5 C 14 3 18 7 18 10 C 18 7 22 3 27 5 C 34 8 32 18 18 28 Z" fill="none" stroke="url(#dg-ct-9)" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 1.87s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 36 36" style={{ position: 'absolute', top: '79.2%', left: '24.6%', width: '1.70rem', height: '1.7rem', overflow: 'visible', opacity: '0.75', transform: 'rotate(-7deg)', animation: 'tk 6.50s ease-in-out 3.60s infinite' }}><path d="M18 3 22 14 33 14 24 21 27 32 18 25 9 32 12 21 3 14 14 14 Z" fill="none" stroke="#e8b64a" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 2.05s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 40 30" style={{ position: 'absolute', top: '85.58%', left: '87.99%', width: '1.87rem', height: '1.4rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(10deg)', animation: 'sw 11.64s ease-in-out -7.70s infinite, rk 14.5s ease-in-out infinite' }}><path d="M4 22 C14 8 22 6 34 10" fill="none" stroke="#7daa76" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 2.23s forwards' }}></path><path d="M6 26 C16 12 24 10 36 14" fill="none" stroke="#7daa76" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 2.45s forwards' }}></path></svg>
    <svg aria-hidden="true" viewBox="0 0 30 30" style={{ position: 'absolute', top: '3.19%', left: '92.3%', width: '1.10rem', height: '1.1rem', overflow: 'visible', opacity: '0.62', transform: 'rotate(-11deg)', animation: 'sw 12.08s ease-in-out -8.40s infinite, rk 15.0s ease-in-out infinite' }}><path d="M5 6 C12 13 18 19 25 25" fill="none" stroke="#b58ce8" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 2.41s forwards' }}></path><path d="M25 6 C18 12 12 18 5 25" fill="none" stroke="#b58ce8" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round" pathLength="1" style={{ '--L': '1', strokeDasharray: '1', strokeDashoffset: '0', animation: 'dw 1.15s ease-in-out 2.63s forwards' }}></path></svg>
    <span aria-hidden="true" style={{ position: 'absolute', top: '93.93%', left: '80.35%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '1.05rem', lineHeight: '1', color: '#e58d55', animation: 'tk 3.0s ease-in-out 0.0s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '7.01%', left: '2.65%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.8rem', lineHeight: '1', color: '#d080cc', animation: 'tk 3.8s ease-in-out 0.7s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '55.83%', left: '40.73%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.75rem', lineHeight: '1', color: '#7daa76', animation: 'tk 4.6s ease-in-out 1.4s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '79.88%', left: '74.14%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.9rem', lineHeight: '1', color: '#b58ce8', animation: 'tk 5.4s ease-in-out 2.1s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '61.65%', left: '71.69%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.85rem', lineHeight: '1', color: '#6fb8ae', animation: 'tk 3.0s ease-in-out 2.8s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '64.74%', left: '22.11%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.95rem', lineHeight: '1', color: '#d080cc', animation: 'tk 3.8s ease-in-out 0.0s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '70.99%', left: '89.42%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.8rem', lineHeight: '1', color: '#6fb8ae', animation: 'tk 4.6s ease-in-out 0.7s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '31.37%', left: '9.76%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.9rem', lineHeight: '1', color: '#e58d55', animation: 'tk 5.4s ease-in-out 1.4s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '28.95%', left: '4.78%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.72rem', lineHeight: '1', color: '#b58ce8', rotate: '14deg', textShadow: '0 0 7px #b58ce866', animation: 'tk 4.03s ease-in-out 3.86s infinite' }}>✚</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '83.79%', left: '33.69%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '1.28rem', lineHeight: '1', color: '#e58d55', rotate: '-6deg', textShadow: '0 0 7px #e58d5566', animation: 'tk 5.98s ease-in-out 0.13s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '36.96%', left: '22.35%', fontFamily: 'Caveat,cursive', fontSize: '0.85rem', lineHeight: '1', color: '#9a6be0', rotate: '11deg', textShadow: '0 0 7px #9a6be066', animation: 'tk 5.01s ease-in-out 0.72s infinite' }}>✚</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '17.81%', left: '10.51%', fontFamily: 'Caveat,cursive', fontSize: '0.85rem', lineHeight: '1', color: '#e58d55', rotate: '-7deg', textShadow: '0 0 7px #e58d5566', animation: 'tk 3.61s ease-in-out 2.25s infinite' }}>✚</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '84.15%', left: '90.03%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '1.1rem', lineHeight: '1', color: '#9a6be0', rotate: '1deg', textShadow: '0 0 7px #9a6be066', animation: 'tk 4.12s ease-in-out 2.94s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '30.82%', left: '80.58%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '1.1rem', lineHeight: '1', color: '#7daa76', rotate: '7deg', textShadow: '0 0 7px #7daa7666', animation: 'tk 4.33s ease-in-out 3.36s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '14.24%', left: '67.18%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.85rem', lineHeight: '1', color: '#7daa76', rotate: '6deg', textShadow: '0 0 7px #7daa7666', animation: 'tk 4.86s ease-in-out 3.65s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '78.89%', left: '33.18%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.72rem', lineHeight: '1', color: '#d080cc', rotate: '-7deg', textShadow: '0 0 7px #d080cc66', animation: 'tk 4.95s ease-in-out 0.17s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '32.51%', left: '44.08%', fontFamily: 'Caveat,cursive', fontSize: '0.72rem', lineHeight: '1', color: '#e58d55', rotate: '-6deg', textShadow: '0 0 7px #e58d5566', animation: 'tk 4.09s ease-in-out 3.26s infinite' }}>✚</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '22.30%', left: '4.58%', fontFamily: 'Caveat,cursive', fontSize: '1.1rem', lineHeight: '1', color: '#7daa76', rotate: '-2deg', textShadow: '0 0 7px #7daa7666', animation: 'tk 3.03s ease-in-out 0.80s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '45.15%', left: '19.64%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.95rem', lineHeight: '1', color: '#9a6be0', rotate: '-4deg', textShadow: '0 0 7px #9a6be066', animation: 'tk 4.39s ease-in-out 3.59s infinite' }}>✚</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '83.81%', left: '72.18%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.85rem', lineHeight: '1', color: '#e58d55', rotate: '5deg', textShadow: '0 0 7px #e58d5566', animation: 'tk 5.11s ease-in-out 1.34s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '22.38%', left: '57.26%', fontFamily: 'Caveat,cursive', fontSize: '0.95rem', lineHeight: '1', color: '#6fb8ae', rotate: '-15deg', textShadow: '0 0 7px #6fb8ae66', animation: 'tk 5.14s ease-in-out 2.56s infinite' }}>✧</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '43.66%', left: '5.78%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '1.28rem', lineHeight: '1', color: '#d080cc', rotate: '14deg', textShadow: '0 0 7px #d080cc66', animation: 'tk 3.58s ease-in-out 1.21s infinite' }}>✚</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '17.18%', left: '83.99%', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.85rem', lineHeight: '1', color: '#e58d55', rotate: '-10deg', textShadow: '0 0 7px #e58d5566', animation: 'tk 5.47s ease-in-out 3.08s infinite' }}>✦</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '45.03%', left: '23.35%', width: '6.6px', height: '6.6px', borderRadius: '999px', background: 'radial-gradient(circle,#dfe6ff,transparent 70%)', boxShadow: '0 0 14.5px #dfe6ff', animation: 'tw 2.82s ease-in-out 0.62s infinite' }}></span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '24.69%', left: '28.98%', width: '3.2px', height: '3.2px', borderRadius: '999px', background: 'radial-gradient(circle,#ffc0e0,transparent 70%)', boxShadow: '0 0 7.0px #ffc0e0', animation: 'tw 3.09s ease-in-out 4.09s infinite' }}></span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '94.63%', left: '31.10%', width: '6.1px', height: '6.1px', borderRadius: '999px', background: 'radial-gradient(circle,#ffd9a8,transparent 70%)', boxShadow: '0 0 13.4px #ffd9a8', animation: 'tw 4.25s ease-in-out 0.69s infinite' }}></span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '50.00%', left: '3.80%', width: '4.1px', height: '4.1px', borderRadius: '999px', background: 'radial-gradient(circle,#cdbcff,transparent 70%)', boxShadow: '0 0 9.0px #cdbcff', animation: 'tw 3.17s ease-in-out 4.06s infinite' }}></span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '23.37%', left: '65.68%', width: '3.8px', height: '3.8px', borderRadius: '999px', background: 'radial-gradient(circle,#a8e6d8,transparent 70%)', boxShadow: '0 0 8.4px #a8e6d8', animation: 'tw 4.93s ease-in-out 0.18s infinite' }}></span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '11.59%', left: '70.06%', width: '4.2px', height: '4.2px', borderRadius: '999px', background: 'radial-gradient(circle,#ffc0e0,transparent 70%)', boxShadow: '0 0 9.2px #ffc0e0', animation: 'tw 3.19s ease-in-out 1.57s infinite' }}></span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '48.59%', left: '27.57%', width: '3.0px', height: '3.0px', borderRadius: '999px', background: 'radial-gradient(circle,#ffc0e0,transparent 70%)', boxShadow: '0 0 6.6px #ffc0e0', animation: 'tw 6.00s ease-in-out 0.08s infinite' }}></span>
  </div>

  <div aria-hidden="true" style={{ position: 'absolute', inset: '0', zIndex: '0', pointerEvents: 'none', overflow: 'hidden' }} data-motion-deco="">
    <span aria-hidden="true" style={{ position: 'absolute', top: '86.4%', left: '19.6%', width: '10rem', fontFamily: 'Caveat,cursive', fontSize: '0.98rem', lineHeight: '1.25', letterSpacing: '0.01em', color: '#7e9c8a', opacity: '0.8', textShadow: '0 1px 1px rgba(0,0,0,0.7)', transform: 'rotate(4deg)' }}>you found the quiet part</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '79.2%', left: '55.8%', width: '10rem', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.66rem', lineHeight: '1.25', letterSpacing: '0.01em', color: '#9c8f7c', opacity: '0.8', textShadow: '0 1px 1px rgba(0,0,0,0.7)', transform: 'rotate(-3deg)' }}>handmade takes longer, means more</span>
    <span aria-hidden="true" style={{ position: 'absolute', top: '92.1%', left: '66.4%', width: '10rem', fontFamily: 'Caveat,cursive', fontSize: '0.98rem', lineHeight: '1.25', letterSpacing: '0.01em', color: '#a89070', opacity: '0.8', textShadow: '0 1px 1px rgba(0,0,0,0.7)', transform: 'rotate(2deg)' }}>i left a heart in the code</span>
  </div>

  <div style={{ position: 'absolute', inset: '0', pointerEvents: 'none', zIndex: '0' }} data-motion-deco="">{V.stars}</div>

  <img loading="lazy" decoding="async" src="/photos/contact-ghost.webp" alt="" aria-hidden="true" data-r="ghost" style={{ position: 'absolute', right: 'clamp(-1rem, 22vw - 17rem, 3rem)', bottom: '10rem', height: 'clamp(30rem, 50vw, 58rem)', width: 'auto', zIndex: '0', pointerEvents: 'none', opacity: '0.29', filter: 'grayscale(0.5) contrast(1.12) brightness(1.04) saturate(1.08)', WebkitMaskImage: 'linear-gradient(96deg, transparent 4%, #000 26%), linear-gradient(#000 82%, transparent 100%)', maskImage: 'linear-gradient(96deg, transparent 4%, #000 26%), linear-gradient(#000 82%, transparent 100%)', WebkitMaskComposite: 'source-in', maskComposite: 'intersect' }} />
  <span aria-hidden="true" data-r="ghost" style={{ position: 'absolute', right: 'clamp(0rem, 22vw - 19rem, 5rem)', bottom: '16rem', width: 'clamp(18rem, 28vw, 32rem)', height: 'clamp(18rem, 28vw, 32rem)', zIndex: '0', pointerEvents: 'none', borderRadius: '50%', background: 'radial-gradient(closest-side, rgba(181,140,232,0.15), rgba(229,141,85,0.07) 58%, transparent 78%)', filter: 'blur(14px)' }}></span>

  <nav aria-label="Sections" data-r="nav" style={{ position: 'fixed', right: '0.9rem', top: '50%', transform: 'translateY(-50%)', zIndex: '20', display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
    <span aria-hidden="true" data-r="thread" style={{ position: 'absolute', right: '1.3rem', marginRight: '-0.5px', top: '1.7rem', bottom: '-1.1rem', width: '1px', background: 'linear-gradient(180deg,transparent,rgba(180,168,140,0.55) 8%,rgba(180,168,140,0.55) 92%,transparent)', transformOrigin: 'top', animation: 'navthread .9s cubic-bezier(.2,.8,.25,1) both' }}></span>
    <span aria-hidden="true" data-r="shine" style={{ position: 'absolute', right: '1.3rem', marginRight: '-0.5px', top: '1.7rem', bottom: '-1.1rem', width: '1px', overflow: 'hidden' }}><span style={{ position: 'absolute', left: '0', top: '-2.6rem', width: '1px', height: '2.6rem', background: 'linear-gradient(180deg,transparent,rgba(255,240,205,0.95),transparent)', animation: 'threadshine 9.5s ease-in-out 2.2s infinite' }}></span></span>
    <span aria-hidden="true" data-r="index" style={{ paddingRight: '0.45rem', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.6rem', letterSpacing: '0.22em', color: '#a89e8d', animation: 'navfade .7s ease .42s both' }}>INDEX</span>
    <a href="/" data-r="beadlink" style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.6rem', height: '2.75rem', paddingRight: '0.85rem', transition: 'transform .3s cubic-bezier(.2,.8,.25,1)' }} className="chv1">
      <span style={{ fontFamily: '\'Playfair Display\',serif', fontSize: '0.68rem', fontWeight: '500', letterSpacing: '0.2em', textTransform: 'uppercase', whiteSpace: 'nowrap', color: '#b3a894', animation: 'navlabel .6s cubic-bezier(.2,.8,.25,1) 0.58s both' }}>Home</span>
      <span aria-hidden="true" style={{ flex: '0 0 auto', display: 'grid', placeItems: 'center', width: '0.9rem', height: '0.9rem', animation: 'navbead .55s cubic-bezier(.2,.8,.25,1) 0.50s both' }}><span style={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', background: 'radial-gradient(circle at 32% 26%, #f0dda6, #9c8149 62%, #4e3d1a)', boxShadow: '0 1px 2px rgba(0,0,0,0.65)' }}></span></span>
    </a>
    <a href="/about" data-r="beadlink" style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.6rem', height: '2.75rem', paddingRight: '0.85rem', transition: 'transform .3s cubic-bezier(.2,.8,.25,1)' }} className="chv1">
      <span style={{ fontFamily: '\'Playfair Display\',serif', fontSize: '0.68rem', fontWeight: '500', letterSpacing: '0.2em', textTransform: 'uppercase', whiteSpace: 'nowrap', color: '#b3a894', animation: 'navlabel .6s cubic-bezier(.2,.8,.25,1) 0.69s both' }}>About</span>
      <span aria-hidden="true" style={{ flex: '0 0 auto', display: 'grid', placeItems: 'center', width: '0.9rem', height: '0.9rem', animation: 'navbead .55s cubic-bezier(.2,.8,.25,1) 0.61s both' }}><span style={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', background: 'radial-gradient(circle at 30% 24%, #ffffff, #e9e0cb 38%, #b8ac93 70%, #6f6650)', boxShadow: '0 1px 2px rgba(0,0,0,0.65)' }}></span></span>
    </a>
    <a href="/skills" data-r="beadlink" style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.6rem', height: '2.75rem', paddingRight: '0.85rem', transition: 'transform .3s cubic-bezier(.2,.8,.25,1)' }} className="chv1">
      <span style={{ fontFamily: '\'Playfair Display\',serif', fontSize: '0.68rem', fontWeight: '500', letterSpacing: '0.2em', textTransform: 'uppercase', whiteSpace: 'nowrap', color: '#b3a894', animation: 'navlabel .6s cubic-bezier(.2,.8,.25,1) 0.80s both' }}>Skills</span>
      <span aria-hidden="true" style={{ flex: '0 0 auto', display: 'grid', placeItems: 'center', width: '0.9rem', height: '0.9rem', animation: 'navbead .55s cubic-bezier(.2,.8,.25,1) 0.72s both' }}><span style={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', background: 'radial-gradient(circle at 32% 26%, #b6d4c2, #5d8a70 58%, #223c2c)', boxShadow: '0 1px 2px rgba(0,0,0,0.65)' }}></span></span>
    </a>
    <a href="/projects" data-r="beadlink" style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.6rem', height: '2.75rem', paddingRight: '0.85rem', transition: 'transform .3s cubic-bezier(.2,.8,.25,1)' }} className="chv1">
      <span style={{ fontFamily: '\'Playfair Display\',serif', fontSize: '0.68rem', fontWeight: '500', letterSpacing: '0.2em', textTransform: 'uppercase', whiteSpace: 'nowrap', color: '#b3a894', animation: 'navlabel .6s cubic-bezier(.2,.8,.25,1) 0.91s both' }}>Projects</span>
      <span aria-hidden="true" style={{ flex: '0 0 auto', display: 'grid', placeItems: 'center', width: '0.9rem', height: '0.9rem', animation: 'navbead .55s cubic-bezier(.2,.8,.25,1) 0.83s both' }}><span style={{ width: '0.5rem', height: '0.5rem', borderRadius: '50%', background: 'radial-gradient(circle at 32% 26%, #e2909a, #a33f4a 56%, #3d1016)', boxShadow: '0 1px 2px rgba(0,0,0,0.65)' }}></span></span>
    </a>
    <a href="/contact" data-r="beadlink" aria-current="page" style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.6rem', height: '2.75rem', paddingRight: '0.85rem', transition: 'transform .3s cubic-bezier(.2,.8,.25,1)' }} className="chv1">
      <span style={{ fontFamily: '\'Playfair Display\',serif', fontSize: '0.74rem', fontWeight: '700', letterSpacing: '0.2em', textTransform: 'uppercase', whiteSpace: 'nowrap', color: '#f2ece0', animation: 'navlabel .6s cubic-bezier(.2,.8,.25,1) 1.02s both' }}>Contact</span>
      <span aria-hidden="true" style={{ flex: '0 0 auto', display: 'grid', placeItems: 'center', width: '0.9rem', height: '0.9rem', animation: 'navbead .55s cubic-bezier(.2,.8,.25,1) 0.94s both' }}><span style={{ width: '0.72rem', height: '0.72rem', borderRadius: '50%', background: 'radial-gradient(circle at 28% 22%, #ffffff, #f2ece0 40%, #c4bcaa 74%, #7d7666)', boxShadow: '0 0 11px rgba(242,236,224,0.42), 0 1px 3px rgba(0,0,0,0.65)', animation: 'beadbreathe 4.6s ease-in-out 1.7s infinite' }}></span></span>
    </a>
    <a href="/guruprasad-jena-resume.pdf" download="Guruprasad-Jena-Resume.pdf" type="application/pdf" data-r="railaction" aria-label="Download résumé (PDF)" style={{ position: 'relative', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '0.6rem', height: '2.4rem', paddingRight: '0.85rem', transition: 'transform .3s cubic-bezier(.2,.8,.25,1)' }} className="chv1"><span style={{ fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.6rem', fontWeight: '600', letterSpacing: '0.2em', textTransform: 'uppercase', whiteSpace: 'nowrap', color: '#e58d55', animation: 'navlabel .6s cubic-bezier(.2,.8,.25,1) 1.02s both' }}>Résumé</span><span aria-hidden="true" style={{ flex: '0 0 auto', display: 'grid', placeItems: 'center', width: '0.9rem', height: '0.9rem', animation: 'navbead .55s cubic-bezier(.2,.8,.25,1) 1.06s both' }}><svg viewBox="0 0 24 24" style={{ width: '0.78rem', height: '0.78rem', color: '#e58d55' }} fill="none" stroke="currentColor" strokeWidth="2.1" strokeLinecap="round" strokeLinejoin="round"><path d="M12 4v11m0 0-4-4m4 4 4-4" /><path d="M5 19h14" /></svg></span></a>
  </nav>

  <div style={{ position: 'relative', zIndex: '1', padding: 'clamp(1.6rem,3.4vw,3rem) clamp(9.25rem,6.6vw,10rem) clamp(3.5rem,6vw,5rem) clamp(4rem,4.4vw,5.5rem)', maxWidth: '96rem' }} data-r="page">

    <div style={{ position: 'relative', paddingLeft: '2.25rem', maxWidth: '52rem' }}>
      <span aria-hidden="true" style={{ position: 'absolute', left: '0', top: '0.55rem', bottom: '0.5rem', width: '1px', background: 'linear-gradient(180deg,rgba(229,141,85,0.55),rgba(229,141,85,0.06))' }}></span>

      <p style={{ margin: '0', display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.55rem', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.66rem', fontWeight: '500', letterSpacing: '0.2em', color: '#9c8b6d' }} data-motion="kicker">
        <span aria-hidden="true" style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#7daa76', boxShadow: '0 0 8px rgba(125,170,118,0.8)' }}></span>OPEN TO WORK<span aria-hidden="true" style={{ opacity: '0.35' }}>/</span>ODISHA · UTC+5:30<span aria-hidden="true" style={{ opacity: '0.35' }}>/</span>REPLIES UNDER 12H
      </p>

      <h1 style={{ margin: '1.6rem 0 0', fontFamily: '\'Playfair Display\',serif', fontSize: 'clamp(2.9rem,6.5vw,5rem)', fontWeight: '500', fontStyle: 'italic', letterSpacing: '-0.015em', lineHeight: '0.95', color: '#f5efe7' }} data-motion="head">Write to me.</h1>

      <p style={{ margin: '1.3rem 0 0', maxWidth: '30rem', fontFamily: 'Spectral,serif', fontSize: '1.08rem', lineHeight: '1.8', color: '#c8bba8', textWrap: 'pretty' }} data-motion="line">A role, a contract, or a question about something I built. No forms — just the address. I answer every real message, <span data-mark>usually the same day</span>.</p>

      <a href="mailto:guruprasadjena989@gmail.com?subject=Hello%20Guru" style={{ marginTop: '2.9rem', display: 'inline-block', paddingBottom: '0.4rem', fontFamily: 'Spectral,serif', fontSize: 'clamp(1.35rem,3.4vw,2.35rem)', letterSpacing: '-0.015em', color: '#e58d55', borderBottom: '1px solid rgba(229,141,85,0.4)', transition: 'color .22s ease, border-color .22s ease' }} data-motion="line" className="chv2">guruprasadjena989@gmail.com</a>

      <div style={{ marginTop: '2.9rem', paddingTop: '1.2rem', borderTop: '1px solid rgba(229,141,85,0.14)', display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '0.9rem 1.5rem' }} data-motion="line">
        <a href="https://github.com/jaga42-ui" target="_blank" rel="noopener" style={{ fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.72rem', fontWeight: '500', letterSpacing: '0.16em', color: '#ccbba8', transition: 'color .2s ease' }} className="chv3">GITHUB</a>
        <span aria-hidden="true" style={{ width: '1px', height: '0.9rem', background: 'rgba(229,141,85,0.22)' }}></span>
        <a href="https://www.linkedin.com/in/guruprasad-jena" target="_blank" rel="noopener" style={{ fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.72rem', fontWeight: '500', letterSpacing: '0.16em', color: '#ccbba8', transition: 'color .2s ease' }} className="chv3">LINKEDIN</a>
        <span aria-hidden="true" style={{ width: '1px', height: '0.9rem', background: 'rgba(229,141,85,0.22)' }}></span>
        <a href="/guruprasad-jena-resume.pdf" download="Guruprasad-Jena-Resume.pdf" type="application/pdf" style={{ fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.72rem', fontWeight: '500', letterSpacing: '0.16em', color: '#ccbba8', transition: 'color .2s ease' }} className="chv3">RÉSUMÉ</a>
        <span aria-hidden="true" style={{ flex: '1' }}></span>
        <span style={{ fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.64rem', letterSpacing: '0.14em', whiteSpace: 'nowrap', color: '#a29584' }}>FULL-STACK · TS · NEXT · NODE · MONGO</span>
      </div>
    </div>

    <div style={{ marginTop: '4.5rem', paddingTop: '1.6rem', borderTop: '1px solid rgba(229,141,85,0.12)', display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,13rem),1fr))', gap: '2rem 3rem', maxWidth: '62rem' }}>
      <div data-motion="line">
        <p style={{ margin: '0', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.62rem', fontWeight: '500', letterSpacing: '0.2em', color: '#9c8b6d' }}>AVAILABILITY</p>
        <p style={{ margin: '0.5rem 0 0', fontFamily: 'Spectral,serif', fontSize: '1rem', lineHeight: '1.65', color: '#d8cbb6' }}>Immediately — full-time or contract.</p>
      </div>
      <div data-motion="line">
        <p style={{ margin: '0', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.62rem', fontWeight: '500', letterSpacing: '0.2em', color: '#9c8b6d' }}>WHERE</p>
        <p style={{ margin: '0.5rem 0 0', fontFamily: 'Spectral,serif', fontSize: '1rem', lineHeight: '1.65', color: '#d8cbb6' }}>Odisha, India. Remote, or relocating.</p>
      </div>
      <div data-motion="line">
        <p style={{ margin: '0', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.62rem', fontWeight: '500', letterSpacing: '0.2em', color: '#9c8b6d' }}>OVERLAP</p>
        <p style={{ margin: '0.5rem 0 0', fontFamily: 'Spectral,serif', fontSize: '1rem', lineHeight: '1.65', color: '#d8cbb6' }}>Six hours with London, four with New York.</p>
      </div>
      <div data-motion="line">
        <p style={{ margin: '0', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.62rem', fontWeight: '500', letterSpacing: '0.2em', color: '#9c8b6d' }}>EVIDENCE</p>
        <p style={{ margin: '0.5rem 0 0', fontFamily: 'Spectral,serif', fontSize: '1rem', lineHeight: '1.65', color: '#d8cbb6' }}>Four products live — <a href="/projects" data-r="beadlink" style={{ borderBottom: '1px solid rgba(229,141,85,0.4)' }}>read the sheets</a>.</p>
      </div>
    </div>

    <div style={{ marginTop: '4rem', display: 'flex', flexWrap: 'wrap', alignItems: 'flex-end', justifyContent: 'space-between', gap: '1.2rem', maxWidth: '62rem' }} data-motion="line">
      <p style={{ margin: '0', fontFamily: 'Caveat,cursive', fontSize: '1.9rem', lineHeight: '1', color: '#e58d55' }}>— Guru</p>
      <p style={{ margin: '0', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.66rem', letterSpacing: '0.12em', color: '#a29584' }}>status: 200 OK if you say hi</p>
    </div>

  </div>

  <div aria-hidden="true" style={{ position: 'absolute', bottom: '1.55rem', left: '6rem', right: '2rem', height: '1px', background: 'linear-gradient(90deg,transparent,rgba(224,214,188,0.16) 12%,rgba(224,214,188,0.16) 88%,transparent)', pointerEvents: 'none' }}></div>
  <div aria-hidden="true" style={{ position: 'absolute', bottom: '0.625rem', left: '6rem', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.6rem', letterSpacing: '0.08em', color: 'rgba(224,214,188,0.45)' }}>NO. 07</div>
  <div aria-hidden="true" style={{ position: 'absolute', bottom: '0.625rem', right: '2rem', fontFamily: '\'JetBrains Mono\',monospace', fontSize: '0.6rem', letterSpacing: '0.08em', color: 'rgba(224,214,188,0.45)' }}>REV 1.07 · 4f2a9c1</div>
</div>
</>
    );
  }
}

Page.defaultProps = {
  starfield: true,
};

export default function ContactScreen() {
  return <Page />;
}
