/* Regenerates app/ from the .dc.html design sources.
   Re-runnable: edit a source, `npm run pages`, get the same tree back.

     app/page.jsx  app/about/page.jsx  app/skills/page.jsx
     app/projects/page.jsx  app/contact/page.jsx
     app/hover.css     one rule per style-hover / style-active / style-focus
     app/globals.css   the union of the five <helmet><style> blocks

   Design decisions are not made here. The only transformations are the ones
   listed in tools/dc2next.js plus the CSS union below, which collapses the
   rules the five sources share and scopes the ones they disagree on.        */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { convert } from './dc2next.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'design_handoff_scrapbook_portfolio', 'design');

const PAGES = [
  { file: 'Home.dc.html', dir: 'app', component: 'HomeScreen', prefix: 'h', label: 'Home' },
  { file: 'About.dc.html', dir: 'app/about', component: 'AboutScreen', prefix: 'a', label: 'About' },
  { file: 'Skills.dc.html', dir: 'app/skills', component: 'SkillsScreen', prefix: 's', label: 'Skills' },
  { file: 'Projects.dc.html', dir: 'app/projects', component: 'ProjectsScreen', prefix: 'p', label: 'Projects' },
  { file: 'Contact.dc.html', dir: 'app/contact', component: 'ContactScreen', prefix: 'c', label: 'Contact' },
];

/* One-line summaries for per-route metadata. The sources carry a <title> but no
   description; these are the §5 character notes from the handoff, verbatim. */
const DESCRIPTIONS = {
  Home: 'Full-stack developer. Four products live, repos public — a scrapbook of the work and the person behind it.',
  About: 'The long-form version: how I got here, what I studied, and what I keep coming back to.',
  Skills: 'The stack I build with and the tools I actually reach for, rated honestly.',
  Projects: 'Four case files — Umbrix, GetFreeToolsAI, Veritas Picks and Sahayam — plotted as blueprint sheets.',
  Contact: 'Open to work from Odisha, India. One address, three links, and a reply within the day.',
};

/* ------------------------------------------------------------------ pages */

const hoverOut = [
  '/* Generated by tools/build.mjs — do not hand-edit.',
  '   One rule per style-hover / style-active / style-focus attribute in the .dc.html sources.',
  '   !important is required: the element also carries an inline style, which would otherwise',
  '   win over any class. Values verbatim. */',
  '',
];

for (const p of PAGES) {
  const src = readFileSync(join(SRC, p.file), 'utf8');
  const { file, hoverRules } = convert(src, { component: p.component, prefix: p.prefix });
  writeFileSync(join(ROOT, p.dir, 'screen.jsx'), file);

  /* The screen is a client component (state, refs, timers). page.jsx stays a server
     component so each route keeps its own <title> from the source's <helmet>. */
  const title = (/<title>([\s\S]*?)<\/title>/.exec(src) || [, p.label])[1].trim();
  writeFileSync(join(ROOT, p.dir, 'page.jsx'),
    'import ' + p.component + " from './screen';\n\n" +
    'export const metadata = {\n' +
    '  title: ' + JSON.stringify(title) + ',\n' +
    '  description: ' + JSON.stringify(DESCRIPTIONS[p.label]) + ',\n' +
    '};\n\n' +
    'export default function Page() {\n  return <' + p.component + ' />;\n}\n');

  hoverOut.push('/* ' + p.label.toLowerCase() + ' */');
  for (const r of hoverRules) {
    const decls = r.css
      .split(/;(?![^(]*\))/)
      .map((d) => d.trim())
      .filter(Boolean)
      .map((d) => {
        const i = d.indexOf(':');
        return d.slice(0, i).trim() + ': ' + d.slice(i + 1).trim() + ' !important';
      });
    hoverOut.push('.' + r.cls + r.sel + ' { ' + decls.join('; ') + '; }');
  }
  hoverOut.push('');
  console.log((p.dir + '/screen.jsx').padEnd(28), file.length.toString().padStart(7), 'chars,', hoverRules.length, 'hover rules');
}

writeFileSync(join(ROOT, 'app/hover.css'), hoverOut.join('\n'));

/* -------------------------------------------------------------- globals.css */

/* split a stylesheet into top-level rules; comments are dropped */
function splitRules(css) {
  const out = [];
  let i = 0, buf = '';
  while (i < css.length) {
    if (css[i] === '/' && css[i + 1] === '*') {
      const e = css.indexOf('*/', i);
      i = e < 0 ? css.length : e + 2;
      continue;
    }
    if (css[i] === '{') {
      let depth = 0, j = i;
      for (; j < css.length; j++) {
        if (css[j] === '{') depth++;
        else if (css[j] === '}') { depth--; if (!depth) break; }
      }
      out.push((buf + css.slice(i, j + 1)).trim());
      buf = '';
      i = j + 1;
      continue;
    }
    buf += css[i++];
  }
  return out.filter(Boolean);
}

const selOf = (r) => r.slice(0, r.indexOf('{')).replace(/\s+/g, ' ').trim();
const bodyOf = (r) => r.slice(r.indexOf('{') + 1, r.lastIndexOf('}')).trim();

/* Three of the mobile rules select on the literal text of the inline style attribute,
   e.g. [data-r="page"] [style*="flex:1 1"]. That only matches while the attribute reads
   exactly as authored. The moment anything assigns to element.style — React on the
   client, or the motion layer parking a transform — the browser re-serialises the whole
   attribute with a space after every colon and the selector stops matching. (It never
   matches at all in the design tool, which renders entirely on the client; that page's
   own mobile rule silently does nothing there.) Emitting both spellings makes the rule
   fire the way it was written to, whoever last touched the element. */
function expandStyleSelectors(rule) {
  const i = rule.indexOf('{');
  if (i < 0) return rule;
  const prelude = rule.slice(0, i);
  const rest = rule.slice(i);

  if (/^\s*@/.test(prelude)) {
    // an at-rule: expand the rules nested inside it
    const inner = splitRules(rest.slice(1, rest.lastIndexOf('}')));
    if (!inner.length) return rule;
    return prelude + '{\n  ' + inner.map((r) => expandStyleSelectors(r).replace(/\s+/g, ' ')).join('\n  ') + '\n}';
  }
  if (!/\[style\*="[^"]*:(?! )/.test(prelude)) return rule;

  const out = [];
  for (const sel of prelude.split(',').map((s) => s.trim()).filter(Boolean)) {
    let variants = [sel];
    // cross-product: each style matcher independently spaced or unspaced
    const matchers = sel.match(/\[style\*="[^"]*:(?! )[^"]*"\]/g) || [];
    for (const m of matchers) {
      const spaced = m.replace(/:(?! )/, ': ');
      variants = variants.flatMap((v) => [v, v.replace(m, spaced)]);
    }
    for (const v of variants) if (!out.includes(v)) out.push(v);
  }
  return out.join(',\n') + ' ' + rest;
}

const sheets = {};
for (const p of PAGES) {
  const m = /<style>([\s\S]*?)<\/style>/.exec(readFileSync(join(SRC, p.file), 'utf8'));
  sheets[p.label] = splitRules(m[1]);
}

/* Rules Projects states differently from the other four. Each is emitted twice:
   the shared value unscoped, then the Projects value under [data-screen-label="Projects"]
   so both survive exactly as authored. */
const PROJECTS_SCOPED = new Set(['a:hover', '::selection', ':focus-visible']);

/* Projects' `body` is the shared rule minus `color` and `font-family`. `body` cannot be
   re-scoped to a descendant, so its rule is dropped here and the one real consequence —
   the missing font-family — is restored below on the Projects page root. Both pages set
   color:#ede4d8 inline on that same root, so dropping it changes nothing. */
const PROJECTS_DROP = new Set(['body']);

/* Rules are emitted in the order they are encountered, NOT regrouped by kind.
   Two of these pages carry competing !important rules whose winner is decided purely
   by source order — Skills states [data-r="step"]{flex:0 0 calc(33.333% - .9rem)}
   under max-width:1024px and then [data-r="step"]{flex:none} under max-width:700px,
   so hoisting all the 700px rules into one merged block ahead of the 1024px block
   silently flips which one wins below 700px. Duplicates collapse to their first
   appearance, which keeps every page's internal cascade intact. */
const seen = new Set();
const rules = [];
const keyframes = new Set();
let current = null;

for (const p of PAGES) {
  for (const rule of sheets[p.label]) {
    const sel = selOf(rule);

    if (sel.startsWith('@keyframes')) {
      if (keyframes.has(sel)) continue;
      keyframes.add(sel);
    } else if (p.label === 'Projects' && PROJECTS_SCOPED.has(sel)) {
      rules.push({ from: p.label, css: '[data-screen-label="Projects"] ' + sel + ' { ' + bodyOf(rule) + ' }' });
      continue;
    } else if (p.label === 'Projects' && PROJECTS_DROP.has(sel)) {
      continue;
    } else {
      const key = rule.replace(/\s+/g, ' ');
      if (seen.has(key)) continue;
      seen.add(key);
    }
    rules.push({ from: p.label, css: rule });
  }
}

/* Projects' body rule sets no font-family, so its text falls back to the UA default.
   The union carries the other four pages' body rule, so Projects would inherit
   "Patrick Hand" where the source has none. */
rules.push({
  from: 'Projects',
  css: '/* Projects\' source <style> declares no body font-family — restore the UA default there */\n' +
    '[data-screen-label="Projects"] { font-family: initial; }',
});

const body = rules.map((r) => {
  const head = r.from !== current ? ((current ? '\n' : '') + '/* ---- from ' + r.from + ' ---- */\n') : '';
  current = r.from;
  return head + expandStyleSelectors(r.css);
}).join('\n');

const out = [
  '/* Generated by tools/build.mjs — do not hand-edit.',
  '   The union of the five pages\' <helmet><style> blocks, in source order. Values are',
  '   verbatim; duplicated resets and identical @keyframes collapse to their first',
  '   appearance, and the four rules Projects states differently are re-scoped to',
  '   [data-screen-label="Projects"] so both variants survive.',
  '   Order is load-bearing — see the note in tools/build.mjs before rearranging. */',
  '',
  body,
  '',
  '/* Honour the OS setting: the JS layer already no-ops, this stops the CSS loops. */',
  '@media (prefers-reduced-motion: reduce) {',
  '  *, *::before, *::after {',
  '    animation-duration: .001ms !important;',
  '    animation-iteration-count: 1 !important;',
  '    transition-duration: .001ms !important;',
  '  }',
  '  html { scroll-behavior: auto; }',
  '}',
  '',
  '/* Print renders the book flat. */',
  '@media print {',
  '  [data-r="foil"], [data-r="spiral"], [data-r="nav"], [data-motion-deco] { display: none !important; }',
  '  *, *::before, *::after { animation: none !important; transition: none !important; }',
  '  [data-r="page"] { padding: 1.5rem !important; }',
  '  body { background: #fff !important; color: #111 !important; }',
  '}',
  '',
].join('\n');

writeFileSync(join(ROOT, 'app/globals.css'), out);
console.log('\napp/globals.css        ', out.length, 'chars —', rules.length, 'rules in source order',
  '(' + keyframes.size + ' keyframes)');
console.log('app/hover.css          ', hoverOut.join('\n').length, 'chars');
